version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - "railsvolume:/var/lib/mysql"
    deploy:
      mode: global
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=railsapp
      - MYSQL_USER=railsuser
      - MYSQL_PASSWORD=password
    ports:
      - "3307:3306"
  app:
    image: 74744556/sample-rails-app:e26cb669fbd00e345c1aaa05726b4e70e0919a05
    deploy:
      mode: global
    ports:
      - "3001:3000"
    depends_on:
      - db
    links:
      - db
    environment:
      - DB_USER=root
      - DB_NAME=railsapp
      - DB_PASSWORD=password
      - DB_HOST=db

volumes:
  railsvolume:
    driver_opts:
      type: "nfs4"
      o: "addr=192.168.0.238"
      device: ":/mnt/sharedfolder/"

