version: "3.2"

services:
  rsyslog:
    image: jumanjiman/rsyslog
    deploy:
      mode: global
    ports:
      - "514:514"
      - "514:514/udp"
    volumes:
      - type: volume
        source: example
        target: /nfs
        volume:
          nocopy: true
volumes:
  example:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.0.238,nolock,soft,rw"
      device: ":/mnt/sharedfolder"

